version: '3.8'

services:
  db:
    image: postgres:15
    container_name: scooter_db_container
    restart: always
    environment:
      POSTGRES_USER: scooter_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: scooter_rental_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
